# Generated by Django 2.1.3 on 2018-11-22 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_detail', to='servey.Result')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(blank=True, choices=[('Open training session', 'Open training session'), ('Until accuracy threshold achieved', 'Until accuracy threshold achieved')], max_length=255, null=True, verbose_name='Training Type')),
                ('accuracy', models.CharField(blank=True, choices=[('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('95%', '95%')], max_length=255, null=True)),
                ('institution', models.TextField()),
                ('training_level', models.CharField(choices=[('Medical student', 'Medical student'), ('Intern', 'Intern'), ('Resident', 'Resident'), ('Fellow', 'Fellow'), ('Attending', 'Attending'), ('APP', 'APP'), ('Other', 'Other')], max_length=255, verbose_name='Training level')),
                ('experience', models.CharField(blank=True, choices=[('none', 'none'), ('0-10', '0-10'), ('11-20', '11-20'), ('21-50', '21-50'), ('50-100', '50-100'), ('> 100', '> 100')], max_length=255, null=True)),
                ('confidence_level', models.CharField(blank=True, choices=[('Very confident', 'Very confident'), ('confident', 'confident'), ('somewhat confident', 'somewhat confident'), ('somewhat not confident', 'somewhat not confident'), ('not confident', 'not confident'), ('very not confident', 'very not confident')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Path video')),
                ('title', models.TextField(blank=True, verbose_name='Title question')),
                ('answer', models.IntegerField(choices=[(1, 'Answer_1'), (2, 'Answer_2'), (3, 'Answer_3')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resultdetail',
            name='video',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='servey.Video'),
        ),
    ]
