# Generated by Django 2.1.3 on 2018-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servey', '0002_auto_20181122_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(blank=True, max_length=255, upload_to='videos/', verbose_name='Upload video'),
        ),
    ]
