# Generated by Django 2.1.3 on 2018-11-22 15:09

from django.db import migrations, models
import servey.validators


class Migration(migrations.Migration):

    dependencies = [
        ('servey', '0003_auto_20181122_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='answer',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(blank=True, max_length=255, upload_to='videos/', validators=[servey.validators.validate_file_extension], verbose_name='Upload video'),
        ),
    ]
